config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',  path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: 'home#index'
  resources :home, only: [:index]
  resources :tips, only: [:index]
  resources :ski_brands

  resources :users do
    resources :skis
  end

  resource :dashboard, only: [:show]

  post "search" => "home#search"
  post "location" => "home#location"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def search
    @search_query = params[:location]
    if @search_query.empty?
      flash[:danger] = 'Not Valid, please try again'
    else
      @output = Weather.service.get_autocomplete_search(@search_query)
    end
  end

  def location
    @location_query = params[:location].pop
    @output = Weather.service.get_current_conditions(@location_query)
  end
end

app/views/home/index.html.erb
<div class="jumbotron container text-center">
  <h1 class="display-4">Wax Guide</h1>
    <p class="lead">Choosing the right wax is hard, so let me help you out </p>
    <hr class="my-4">
    <p>Where are you skiing? Find your location</p>
    <div class="container text-center">
      <%= form_tag search_path, :method => 'POST' do %>
        <div class="form-group">
          <%= text_field_tag 'location', nil, placeholder: "Location Name", class: "form-group" %>
          <%= submit_tag "Search", class: "btn btn-outline-success" %>
        <% end %>
    </div>
</div>

app/views/home/location.html.erb
<% if Weather.error_handling(@output) == true %>
  <%= render 'shared/error_catch' %>
<% else %>
<div class="jumbotron container text-center <%= Weather.adjusted_color(@output) %>">
  <h1 class="display-4">WaxGuide Recomendation</h1>
    <p class="lead">The current temperature is: <%= Weather.metric(@output) %> C or <%= Weather.imperial(@output) %> F</p>
    <p class="lead">Current weather conditions: <%= @output.first[:WeatherText] %> </p>
      <% if @output.first[:PrecipitationType] == true %>
        <%= @output.first[:PrecipitationType] && @output.first[:HasPrecipitation] %>
      <% end %>
    <hr class="my-4">
      The best wax for your conditions is: <%= Weather.description(@output) %>
      <% end %>
    <hr class="my-4">
      <p>Be sure check out the Wax Tips page <%= link_to 'here','/tips' %> for more details.</p> 
</div>

app/views/home/search.html.erb
<div class="jumbotron container text-center">
  <h1 class="display-4">Location Search</h1>
  <hr class="my-4">
    <div class="container text-center">
      <ul class="location-list">
        <% if Weather.error_handling(@output) == true %>
         <%= render 'shared/error_catch' %>
        <% else %>
          <% @output.each do |location| %>
            <li> Location Name: <%=  location["LocalizedName"] %></li>
              <li> State/Country: <%= location["AdministrativeArea"]["ID"] %>, <%= location["AdministrativeArea"]["LocalizedName"] %></li>
                <%= form_tag location_path, :method => 'POST' do %>
                  <div class="form-group">
                    <%= hidden_field 'location', nil, :value => location["Key"], class: "form-group" %>                    
                    <%= submit_tag "Search This Location", class: "btn btn-success location-search" %> 
                    <% end %>
                <hr class="my-4">
              <% end %>
            <% end %>
      </ul>
        <br>
    </div>
    <hr class="my-4">
</div>

app/views/home/zipcode.html.erb
<div class="jumbotron container text-center">
  <h1 class="display-4">Location Search</h1>
  <hr class="my-4">
    <div class="container text-center">
      <ul class="location-list">
        <% if Weather.error_handling(@output) == true %>
          <h4>Sorry! An error has occured. Please search again!</h4>
          <%= link_to 'Home', '/', class: "btn btn-success"%>
        <% else %>
          <% @output.each do |location| %>
            <li> Location Name: <%=  location["LocalizedName"] %></li>
              <li> State/Country: <%= location["AdministrativeArea"]["ID"] %>, <%= location["AdministrativeArea"]["LocalizedName"] %></li>
                <%= form_tag location_path, :method => 'POST' do %>
                  <div class="form-group">
                    <%= hidden_field 'location', nil, :value => location["Key"], class: "form-group" %>                    
                    <%= submit_tag "Search This Location", class: "btn btn-success location-search" %> 
                    <% end %>
                <hr class="my-4">
              <% end %>
            <% end %>
      </ul>
        <br>
    </div>
    <hr class="my-4">
</div>