config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',  path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: 'home#index'
  resources :home, only: [:index]
  resources :tips, only: [:index]
  resources :ski_brands

  resources :users do
    resources :skis
  end

  resource :dashboard, only: [:show]

  post "search" => "home#search"
  post "location" => "home#location"
end

app/models/ski.rb
# frozen_string_literal: true

class Ski < ApplicationRecord
  belongs_to :user
  validates_presence_of :brand, :model, :grind

  scope :cold, -> { where(grind: :cold) }
  scope :warm, -> { where(grind: :warm) }
  scope :wet, -> { where(grind: :wet) }
end

app/controllers/skis_controller.rb
class SkisController < ApplicationController
  before_action :find_user, only: %i[new create show index]
  before_action :find_ski, only: %i[show edit update]

  def new
    @ski = Ski.new
  end

  def edit
    find_ski
  end

  def update
    respond_to do |format|
      if @ski.update!(ski_params)
        format.html {
          redirect_to user_ski_path(@user.id, @ski.id),
          notice: 'these ski details have successfully updated!'
        }
      else
        format.html { redirect_to :edit }
      end
    end
  end

  def create
    @ski = @user.skis.create!(ski_params)
    if @ski.save!
      SkiConfirmationMailer.with(user: @user, ski: @ski).ski_confirmation_email.deliver_now
      flash[:notice] = 'Ski successfully created!'
      redirect_to user_ski_path(@user, @ski)
    else
      render :new
    end
  end

  def show
    find_ski
  end

  def index
    @skis = @user.skis.all
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_ski
    @ski = Ski.find(params[:id])
  end

  def ski_params
    params.require(:ski).permit(
      :brand,
      :model,
      :skate,
      :classic,
      :size,
      :grind,
    )
  end
end

app/views/skis/edit.html.erb
<div class="card">
  <div class="card-block">
    <div class="container">
      <%= form_for(@ski) do |f| %>
      <div class="row">
        <div class="col-md-6">

          <div class="form-group">
            <%= f.label :brand %><br />
            <%= f.text_field :brand, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :model %><br />
            <%= f.text_field :model, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :skate %><br />
            <%= f.check_box :model, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :classic %><br />
            <%= f.check_box :classic, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :size %><br />
            <%= f.text_field :size, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :grind %><br />
            <%= f.text_field :grind, class: 'form-control' %>
          </div>

        </div>
          <div class="actions">
            <%= f.submit "Create", class: "btn btn-success" %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/skis/index.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-8">
        <div class="container">
          <h1><%= @user.name %>'s Skis</h1>
          <%= @skis.inspect %>
          <%= link_to 'Dashboard', dashboard_path %>
          <%= link_to 'Add new ski', new_user_ski_path(current_user.id) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/skis/new.html.erb
<div class="card">
  <div class="card-block">
    <div class="container">
      <%= form_for [@user, @ski] do |f| %>
      <div class="row">
        <div class="col-md-6">

          <div class="form-group">
            <%= f.label :brand %><br />
            <%= f.text_field :brand, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :model %><br />
            <%= f.text_field :model, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :skate %><br />
            <%= f.check_box :skate, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :classic %><br />
            <%= f.check_box :classic, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :size %><br />
            <%= f.text_field :size, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :grind %><br />
            <%= f.text_field :grind, class: 'form-control' %>
          </div>

        </div>
          <div class="actions">
            <%= f.submit "Create", class: "btn btn-success" %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/skis/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
    </div>

    <div class="col-md-5">
      <h1><%= @ski.brand %></h1>

      <hr>

      <em><%= @ski.model %></em>

      <% if @ski.classic == true %>
        <p>Classic</p>
      <% end %>
      <% if @ski.skate == true %>
        <p>Skate</p>
      <% end %>

      <hr>
      <p><%= @ski.size %></p>
      <p><%= @ski.grind %></p>
      <br>
      <%= link_to 'My Gear Closet - all skis', dashboard_path(current_user) %>
      <%= link_to 'Edit/Update Ski Attributes', edit_user_ski_path(current_user, @ski.id) %>
    </div>
  </div>
</div>